batch_size: 1
cutoff_len: 4096
experiment_id: 90e341b9
infer_dtype: bfloat16
low_cpu_mem_usage: true
max_samples: 1000
model_name_or_path: gpt2
rope_scaling_factor: 4
rope_scaling_type: dynamic
save_dir: results/gpt2/dynamic/4096/90e341b9
seed: 42
task: perplexity
timestamp: '2025-08-26T18:03:44.343711'
trust_remote_code: true
use_cache: true
