batch_size: 1
cutoff_len: 8192
experiment_id: 79a49673
infer_dtype: bfloat16
low_cpu_mem_usage: true
max_samples: 1000
model_name_or_path: gpt2
rope_scaling_factor: 2
rope_scaling_type: dynamic
save_dir: results/gpt2/dynamic/8192/79a49673
seed: 42
task: perplexity
timestamp: '2025-08-26T18:03:44.335801'
trust_remote_code: true
use_cache: true
