batch_size: 1
cutoff_len: 4096
experiment_id: 5a8525ed
infer_dtype: bfloat16
low_cpu_mem_usage: true
max_samples: 1000
model_name_or_path: gpt2
rope_scaling_factor: 8
rope_scaling_type: llama3
save_dir: results/gpt2/llama3/4096/5a8525ed
seed: 42
task: perplexity
timestamp: '2025-08-26T18:03:45.444190'
trust_remote_code: true
use_cache: true
